## AIC errors
load("35563325713.Rdat") ## Data generated by Figure3.R with 2000 reps

cairo_pdf(file="aic.pdf", width=7*3/3, height=2.5) 
    data_names <- c("Deteriorating", "Constant", "Empirical")
    par(mfrow=c(1,3),  oma=c(5,5,5,4), mar=c(0,0,0,0))
    plot(deterior_mc, shade_aic=T, show_data=F, shade=F, show_text="",
         legend=TRUE, ylim =c(0,.6), test_dist=T, xlim=c(0,10)) 
    mtext("Probability density", WEST<-2, line=3) 
    mtext(data_names[1], NORTH<-3, cex=par()$cex.lab, line=2) 
    plot(constant_mc, shade_aic=T, show_data=F, shade=F, show_text="",
         legend=TRUE, ylim =c(0,.6), yaxt="n", test_dist=F, xlim=c(0,10)) 
    mtext(data_names[2], NORTH<-3, cex=par()$cex.lab, line=2) 
    mtext("Likelihood Ratio", SOUTH<-1, line=3) 
    plot(deut3_mc, shade_aic=T, show_data=F, shade=F, show_text="",
         legend=TRUE, ylim =c(0,.6), yaxt="n", test_dist=T, xlim=c(0,10))
    mtext(data_names[3], NORTH<-3, cex=par()$cex.lab, line=2) 
     
dev.off()



### Model Choice


